FROM docker.artifactory-dogen.group.echonet/node:22-alpine AS builder

ARG ARTIFACTORY_TOKEN

WORKDIR /app

COPY package.json ./
COPY .npmrc ./

RUN npm install

COPY . .
RUN ./node_modules/.bin/vite build

FROM docker.artifactory-dogen.group.echonet/nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
